spring:
  application:
    name: BoulderBackApplication
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/BoulderDB?currentSchema=boulder
    #url: jdbc:postgresql://dpg-cr4s9ro8fa8c73a721kg-a:5432/climbappdb
    username: pablo
    #username: climbappdb_user
    password: pabloAdm
    #password: N2DGUmuRyaV5WX98T4JMAcc9bL33on3l
    hikari:
      maximum-pool-size: 10
      minimum-idle: 0
      idle-timeout: 600000
      connection-timeout: 50000
  jpa:
    properties:
      hibernate:
        default_schema: boulder #Local
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

server:
  port: 8080
  forward-headers-strategy: framework
  shutdown: graceful

logging:
  level:
    org.springframework: INFO
    org.hibernate: INFO
    com.tfg.boulder_back.BoulderBackApplication: INFO
